Repository Diegogagan2587/Recipe-app-bests-dishes, pull requests merged in 2023-10, with the labels that each got.

#19 Feat/navigation bar
  Gemfile
  Gemfile.lock
  app/assets/images/logo.png
  app/views/layouts/_navbar.html.erb
  app/views/layouts/application.html.erb
  config/database.yml
Labels: enhancement

#21 Feat/food list
  .gitignore
  .ruby-version
  app/assets/stylesheets/foods.css
  app/assets/stylesheets/new_food.css
  app/controllers/foods_controller.rb
  app/views/foods/index.html.erb
  app/views/foods/new.html.erb
  app/views/foods/show.html.erb
  app/views/layouts/_navbar.html.erb
  config/routes.rb
Labels: enhancement

#22 Fix/sign up
  app/controllers/foods_controller.rb
  app/controllers/registrations_controller.rb
  app/views/devise/registrations/new.html.erb
  config/routes.rb
Labels: bug

#26 Feat/tests
  afterr.png
  app/assets/images/icon.png
  app/controllers/home_controller.rb
  app/controllers/recipes_controller.rb
  app/views/devise/registrations/edit.html.erb
  app/views/devise/registrations/new.html.erb
  app/views/devise/sessions/new.html.erb
  app/views/foods/new.html.erb
  app/views/home/index.html.erb
  app/views/layouts/_navbar.html.erb
  app/views/recipes/index.html.erb
  app/views/recipes/public_recipe.html.erb
  before.png
  config/routes.rb
  spec/features/recipe_show_page_spec.rb
  spec/integration/recipe_spec.rb
  spec/models/recipe_spec.rb
  spec/models/user_spec.rb
  spec/rails_helper.rb
  spec/requests/public_recipe_spec.rb
  spec/spec_helper.rb
Labels: test

#25 Feat/test models and shoppin list
  app/controllers/general_shopping_list_controller.rb
  app/controllers/users_controller.rb
  app/models/food.rb
  app/views/foods/index.html.erb
  spec/integration/foods/index_spec.rb
  spec/integration/general_shopping_list/index_spec.rb
  spec/integration/registrations/new_spec.rb
  spec/models/food_spec.rb
  spec/models/recipe_food_spec.rb
  spec/requests/foods/create_spec.rb
  spec/requests/foods/index_spec.rb
  spec/requests/foods/new_spec.rb
  spec/requests/general_shopping_list_controller.rb/index.rb
Labels: documentation
